USE [linxdbDIMSHendok]
GO

/****** Object:  Table [dbo].[tblEmailTypes]    Script Date: 2025/07/10 10:22:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblEmailTypes](
	[intAutoId] [int] IDENTITY(1,1) NOT NULL,
	[strEmailType] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[intAutoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


