SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblStatuses](
	[intStatusId] [int] NOT NULL,
	[strStatus] [nvarchar](50) NULL,
	[strReference] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblStatuses] ADD  CONSTRAINT [PK_tblStatuses] PRIMARY KEY CLUSTERED 
(
	[intStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
